particle = opengles2-book/LinuxX11/Chapter_13/ParticleSystem/CH13_ParticleSystem

default:
	cd opengles2-book/LinuxX11/ && emmake make advanced
	cp $(particle).html .
	cp $(particle).js .
	cp $(particle).data .
	cp $(particle).html.map .
	cp ../memoryprofiler.js .
	cp ../stacktrace.js stacktrace.js

